// <auto-generated>
// THIS (.cs) FILE IS GENERATED BY MPC(MessagePack-CSharp). DO NOT CHANGE IT.
// </auto-generated>

#pragma warning disable 618
#pragma warning disable 612
#pragma warning disable 414
#pragma warning disable 168

#pragma warning disable SA1129 // Do not use default value type constructor
#pragma warning disable SA1200 // Using directives should be placed correctly
#pragma warning disable SA1309 // Field names should not begin with underscore
#pragma warning disable SA1312 // Variable names should begin with lower-case letter
#pragma warning disable SA1403 // File may only contain a single namespace
#pragma warning disable SA1649 // File name should match first type name

namespace MessagePack.Formatters.ColorBallsPuzzle.Gameplay
{
    using global::System.Buffers;
    using global::MessagePack;

    public sealed class CampaignLevelVisualDescModelFormatter : global::MessagePack.Formatters.IMessagePackFormatter<global::ColorBallsPuzzle.Gameplay.CampaignLevelVisualDescModel>
    {
        // scene_address
        private static global::System.ReadOnlySpan<byte> GetSpan_SceneAddress() => new byte[1 + 13] { 173, 115, 99, 101, 110, 101, 95, 97, 100, 100, 114, 101, 115, 115 };

        public void Serialize(ref global::MessagePack.MessagePackWriter writer, global::ColorBallsPuzzle.Gameplay.CampaignLevelVisualDescModel value, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (value is null)
            {
                writer.WriteNil();
                return;
            }

            var formatterResolver = options.Resolver;
            writer.WriteMapHeader(1);
            writer.WriteRaw(GetSpan_SceneAddress());
            formatterResolver.GetFormatterWithVerify<string>().Serialize(ref writer, value.SceneAddress, options);
        }

        public global::ColorBallsPuzzle.Gameplay.CampaignLevelVisualDescModel Deserialize(ref global::MessagePack.MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (reader.TryReadNil())
            {
                return null;
            }

            options.Security.DepthStep(ref reader);
            var formatterResolver = options.Resolver;
            var length = reader.ReadMapHeader();
            var ____result = new global::ColorBallsPuzzle.Gameplay.CampaignLevelVisualDescModel();

            for (int i = 0; i < length; i++)
            {
                var stringKey = global::MessagePack.Internal.CodeGenHelpers.ReadStringSpan(ref reader);
                switch (stringKey.Length)
                {
                    default:
                    FAIL:
                      reader.Skip();
                      continue;
                    case 13:
                        if (!global::System.MemoryExtensions.SequenceEqual(stringKey, GetSpan_SceneAddress().Slice(1))) { goto FAIL; }

                        ____result.SceneAddress = formatterResolver.GetFormatterWithVerify<string>().Deserialize(ref reader, options);
                        continue;

                }
            }

            reader.Depth--;
            return ____result;
        }
    }
}
