// <auto-generated>
// THIS (.cs) FILE IS GENERATED BY MPC(MessagePack-CSharp). DO NOT CHANGE IT.
// </auto-generated>

#pragma warning disable 618
#pragma warning disable 612
#pragma warning disable 414
#pragma warning disable 168

#pragma warning disable SA1129 // Do not use default value type constructor
#pragma warning disable SA1200 // Using directives should be placed correctly
#pragma warning disable SA1309 // Field names should not begin with underscore
#pragma warning disable SA1312 // Variable names should begin with lower-case letter
#pragma warning disable SA1403 // File may only contain a single namespace
#pragma warning disable SA1649 // File name should match first type name

namespace MessagePack.Formatters.ColorBallsPuzzle.Gameplay
{
    using global::System.Buffers;
    using global::MessagePack;

    public sealed class DescriptionsModelFormatter : global::MessagePack.Formatters.IMessagePackFormatter<global::ColorBallsPuzzle.Gameplay.DescriptionsModel>
    {
        // version
        private static global::System.ReadOnlySpan<byte> GetSpan_Version() => new byte[1 + 7] { 167, 118, 101, 114, 115, 105, 111, 110 };
        // campaign
        private static global::System.ReadOnlySpan<byte> GetSpan_Campaign() => new byte[1 + 8] { 168, 99, 97, 109, 112, 97, 105, 103, 110 };

        public void Serialize(ref global::MessagePack.MessagePackWriter writer, global::ColorBallsPuzzle.Gameplay.DescriptionsModel value, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (value is null)
            {
                writer.WriteNil();
                return;
            }

            var formatterResolver = options.Resolver;
            writer.WriteMapHeader(2);
            writer.WriteRaw(GetSpan_Version());
            formatterResolver.GetFormatterWithVerify<global::ColorBallsPuzzle.Gameplay.DescriptionsVersion>().Serialize(ref writer, value.Version, options);
            writer.WriteRaw(GetSpan_Campaign());
            formatterResolver.GetFormatterWithVerify<global::ColorBallsPuzzle.Gameplay.CampaignDescModel>().Serialize(ref writer, value.Campaign, options);
        }

        public global::ColorBallsPuzzle.Gameplay.DescriptionsModel Deserialize(ref global::MessagePack.MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (reader.TryReadNil())
            {
                return null;
            }

            options.Security.DepthStep(ref reader);
            var formatterResolver = options.Resolver;
            var length = reader.ReadMapHeader();
            var ____result = new global::ColorBallsPuzzle.Gameplay.DescriptionsModel();

            for (int i = 0; i < length; i++)
            {
                var stringKey = global::MessagePack.Internal.CodeGenHelpers.ReadStringSpan(ref reader);
                switch (stringKey.Length)
                {
                    default:
                    FAIL:
                      reader.Skip();
                      continue;
                    case 7:
                        if (global::MessagePack.Internal.AutomataKeyGen.GetKey(ref stringKey) != 31084746137298294UL) { goto FAIL; }

                        ____result.Version = formatterResolver.GetFormatterWithVerify<global::ColorBallsPuzzle.Gameplay.DescriptionsVersion>().Deserialize(ref reader, options);
                        continue;
                    case 8:
                        if (global::MessagePack.Internal.AutomataKeyGen.GetKey(ref stringKey) != 7955443133992231267UL) { goto FAIL; }

                        ____result.Campaign = formatterResolver.GetFormatterWithVerify<global::ColorBallsPuzzle.Gameplay.CampaignDescModel>().Deserialize(ref reader, options);
                        continue;

                }
            }

            reader.Depth--;
            return ____result;
        }
    }
}
