// <auto-generated>
// THIS (.cs) FILE IS GENERATED BY MPC(MessagePack-CSharp). DO NOT CHANGE IT.
// </auto-generated>

#pragma warning disable 618
#pragma warning disable 612
#pragma warning disable 414
#pragma warning disable 168

#pragma warning disable SA1129 // Do not use default value type constructor
#pragma warning disable SA1200 // Using directives should be placed correctly
#pragma warning disable SA1309 // Field names should not begin with underscore
#pragma warning disable SA1312 // Variable names should begin with lower-case letter
#pragma warning disable SA1403 // File may only contain a single namespace
#pragma warning disable SA1649 // File name should match first type name

namespace MessagePack.Formatters.ColorBallsPuzzle.Gameplay
{
    using global::System.Buffers;
    using global::MessagePack;

    public sealed class CampaignDescModelFormatter : global::MessagePack.Formatters.IMessagePackFormatter<global::ColorBallsPuzzle.Gameplay.CampaignDescModel>
    {
        // level_descs
        private static global::System.ReadOnlySpan<byte> GetSpan_LevelDescriptions() => new byte[1 + 11] { 171, 108, 101, 118, 101, 108, 95, 100, 101, 115, 99, 115 };
        // levels
        private static global::System.ReadOnlySpan<byte> GetSpan_Levels() => new byte[1 + 6] { 166, 108, 101, 118, 101, 108, 115 };

        public void Serialize(ref global::MessagePack.MessagePackWriter writer, global::ColorBallsPuzzle.Gameplay.CampaignDescModel value, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (value is null)
            {
                writer.WriteNil();
                return;
            }

            var formatterResolver = options.Resolver;
            writer.WriteMapHeader(2);
            writer.WriteRaw(GetSpan_LevelDescriptions());
            formatterResolver.GetFormatterWithVerify<global::System.Collections.ObjectModel.ReadOnlyDictionary<global::ColorBallsPuzzle.Gameplay.CampaignLevelDescId, global::ColorBallsPuzzle.Gameplay.CampaignLevelDescModel>>().Serialize(ref writer, value.LevelDescriptions, options);
            writer.WriteRaw(GetSpan_Levels());
            formatterResolver.GetFormatterWithVerify<global::ColorBallsPuzzle.Gameplay.CampaignLevelDescId[]>().Serialize(ref writer, value.Levels, options);
        }

        public global::ColorBallsPuzzle.Gameplay.CampaignDescModel Deserialize(ref global::MessagePack.MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (reader.TryReadNil())
            {
                return null;
            }

            options.Security.DepthStep(ref reader);
            var formatterResolver = options.Resolver;
            var length = reader.ReadMapHeader();
            var ____result = new global::ColorBallsPuzzle.Gameplay.CampaignDescModel();

            for (int i = 0; i < length; i++)
            {
                var stringKey = global::MessagePack.Internal.CodeGenHelpers.ReadStringSpan(ref reader);
                switch (stringKey.Length)
                {
                    default:
                    FAIL:
                      reader.Skip();
                      continue;
                    case 11:
                        if (!global::System.MemoryExtensions.SequenceEqual(stringKey, GetSpan_LevelDescriptions().Slice(1))) { goto FAIL; }

                        ____result.LevelDescriptions = formatterResolver.GetFormatterWithVerify<global::System.Collections.ObjectModel.ReadOnlyDictionary<global::ColorBallsPuzzle.Gameplay.CampaignLevelDescId, global::ColorBallsPuzzle.Gameplay.CampaignLevelDescModel>>().Deserialize(ref reader, options);
                        continue;
                    case 6:
                        if (global::MessagePack.Internal.AutomataKeyGen.GetKey(ref stringKey) != 126909395920236UL) { goto FAIL; }

                        ____result.Levels = formatterResolver.GetFormatterWithVerify<global::ColorBallsPuzzle.Gameplay.CampaignLevelDescId[]>().Deserialize(ref reader, options);
                        continue;

                }
            }

            reader.Depth--;
            return ____result;
        }
    }
}
